  - name: Installation of openstack-Nova for Ubuntu
    apt:
      name:
        - nova-compute
        - python3-openstackclient
      state: latest
      update_cache: yes
    when: ansible_distribution == "Ubuntu"
